name: drupal-panther

services:
  php:
    type: php:7.1
    via: cli
    xdebug: true

tooling:
  composer:
    service: php
    description: Run composer commands
    cmd:
      - composer
      - --ansi
  
  php:
    service: php